// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {operate} from '../models';

export function CreateFile(arg1:string,arg2:string):Promise<boolean>;

export function GetDirectoryTree(arg1:string):Promise<Array<operate.FileNode>>;
